version: '3'
services:
  web:
    image: nginx:mainline-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # - ./conf/nginx:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx
